"use client";

import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { motion } from "motion/react";
import type { Project } from "@/data/projects";

export function ProjectDetailView({ project }: { project: Project }) {
  return <main className="min-h-screen bg-neutral-950 px-6 pt-36 text-white"><div className="container mx-auto"><Link href="/work" className="mb-12 inline-flex items-center gap-2 text-xs font-mono uppercase tracking-widest text-neutral-500 transition-colors hover:text-white"><ArrowLeft className="h-4 w-4" />Back to Archive</Link><motion.div initial={{ opacity: 0, y: 50 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.8 }} className="mb-24"><div className="mb-16 flex flex-col items-end justify-between gap-8 md:flex-row"><h1 className="text-6xl font-medium leading-[0.9] tracking-tighter md:text-9xl">{project.title}</h1><span className="mb-2 text-sm font-mono text-neutral-400">{project.category} — {project.year}</span></div><div className="aspect-[16/9] overflow-hidden rounded-sm bg-neutral-900"><motion.img initial={{ scale: 1.1 }} animate={{ scale: 1 }} transition={{ duration: 1.5, ease: [0.22, 1, 0.36, 1] }} src={project.image} alt={project.title} className="h-full w-full object-cover" /></div></motion.div><div className="mb-32 grid gap-16 md:grid-cols-[1fr_2fr] md:gap-24"><aside className="space-y-12"><div><span className="mb-2 block text-xs font-mono uppercase tracking-widest text-neutral-600">Client</span><p className="text-xl font-light">{project.client}</p></div><div><span className="mb-2 block text-xs font-mono uppercase tracking-widest text-neutral-600">Role</span><p className="text-xl font-light">{project.role}</p></div><div><span className="mb-2 block text-xs font-mono uppercase tracking-widest text-neutral-600">Year</span><p className="text-xl font-light">{project.year}</p></div></aside><div><p className="text-2xl font-light leading-relaxed text-neutral-300 md:text-4xl">{project.description}</p><div className="mt-16 grid gap-10 border-t border-white/10 pt-16 md:grid-cols-2"><div><span className="mb-3 block text-xs font-mono uppercase tracking-widest text-neutral-600">Challenge</span><p className="leading-relaxed text-neutral-400">{project.challenge}</p></div><div><span className="mb-3 block text-xs font-mono uppercase tracking-widest text-neutral-600">Outcome</span><p className="leading-relaxed text-neutral-400">{project.outcome}</p></div></div><div className="mt-16 grid grid-cols-2 gap-4">{project.gallery.map((image, index) => <div key={image} className="aspect-square overflow-hidden rounded-sm bg-neutral-900"><img src={image} alt={`${project.title} detail ${index + 1}`} className="h-full w-full object-cover opacity-75 grayscale transition-all duration-500 hover:opacity-100 hover:grayscale-0" /></div>)}</div></div></div><div className="border-t border-white/10 py-24 text-center"><Link href="/work" className="group inline-flex flex-col items-center gap-4"><span className="text-xs font-mono uppercase tracking-widest text-neutral-500">Explore more</span><span className="text-6xl font-medium tracking-tighter transition-colors group-hover:text-neutral-400 md:text-8xl">View Archive</span></Link></div></div></main>;
}
